/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomAppBarIcons
///      fonts:
///       - asset: fonts/BottomAppBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomAppBarIcons {
  BottomAppBarIcons._();

  static const _kFontFam = 'BottomAppBarIcons';
  static const String? _kFontPkg = null;

  static const IconData icFavoriteFilled = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData icFavoriteOutlined = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icHomeFilled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icHomeOutlined = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icProfileFilled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icProfileOutlined = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
